# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  hardware.graphics = {
    enable = true;
  };

  services.xserver.videoDrivers = ["nvidia"];

  hardware.nvidia = {
    package = config.boot.kernelPackages.nvidiaPackages.production;
    open = false;
    nvidiaSettings = true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8ab8a27f-d560-4265-a55b-e0fbbd4d5bcd";
      fsType = "ext4";
    };

  #fileSystems."/shared" =
  #  { device = "shared";
  #    fsType = "virtiofs";
  #    # added this line:
  #    options = [ "nofail" ];
  #  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B57-C873";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
